### ISSUE TITLE
Issue when first selected tag has no data

### ISSUE THREAD

**Issue by NedaHassani** [BonyanSystem/ASN1Processor#1]
Hello ,
First of all, thanks for this great processor  Mr. Khoshbakht

I faced a bug when my first selected tags in "CSV Schema" has no data

(79.38 and 79.39 has no data in my asn.1 binary file )

![nifi processor](https://user-images.githubusercontent.com/72344598/107145866-c4d17800-6959-11eb-8655-7a7767cf95d5.png)

**Comment by saeedmkh** [comment]
Solved in 1.8
